[workspace]
resolver = "2"
members = [
    "crates/networking",
    "crates/parser",
    "crates/js-engine",
    "crates/privacy",
    "crates/security",
    "crates/ui",
    "fuzz",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[workspace.dependencies]
bytes = { workspace = true }

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
