[workspace]
members = [
    "crates/antifingerprint",
    "crates/networking",
    "crates/parser",
    "crates/security",
    "crates/tabs",
    "crates/zkvm",
    "fuzz",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Citadel Browser Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/citadel/citadel-browser-rust"

[workspace.dependencies]
# Keep all shared dependencies here
thiserror = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
rustls = "0.21"
rustls-native-certs = "0.6"
hyper-rustls = { version = "0.24", features = ["http2"] }
trust-dns-resolver = "0.23"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
bytes = "1.5"
futures = "0.3"
rand = "0.8"
serde_json = "1.0"
url = "2.4"
html5ever = "0.26"
cssparser = "0.31"
selectors = "0.25"
aes-gcm = { version = "0.10.3", features = ["std"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
tokio-test = "0.4.3"
parking_lot = "0.12"
bincode = "1.3"
blake3 = "1.5"
string-cache = "0.8"
markup5ever = "0.11"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false

[profile.dev]
opt-level = 1
debug = true 