[workspace]
resolver = "2"

[workspace.package]
edition = "2021"

members = [
    "crates/networking",
    "crates/parser",
    "crates/js-engine",
    "crates/privacy",
    "crates/security",
    "crates/ui",
    "fuzz",
]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
