[package]
name = "citadel-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
citadel-networking = { path = "../crates/networking" }

[build-dependencies]
arbitrary = { version = "1", features = ["derive"] }

# Remove the workspace section since this is part of the main workspace

# Add a lib target to satisfy Cargo
[lib]
name = "citadel_fuzz"
path = "src/lib.rs"
