[package]
name = "citadel-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
citadel-networking = { path = "../crates/networking" }

[build-dependencies]
arbitrary = { version = "1", features = ["derive"] }

[workspace]
# This section should NOT be present if it's not the root workspace
